### ISSUE TITLE
No user input for DPS Tracker

### ISSUE THREAD

**Issue by Adam-Anthony** [Adam-Anthony/Practice#1]
- [ ] Add user input via console
- [ ] Add user input via Args
- [ ] Check user input for malformed info
- [ ] Handle off cases, negative numbers
